- name: install yum utils
  yum: 
   name: yum-utils
   state: latest

- name: update cache
  yum:
   update_cache: yes

- name: installing java {{ version }}
  when: version == 11
  shell: amazon-linux-extras install java-openjdk"{{ version}}" -y 

- name: installing java {{ version }}
  when: version == 8
  yum:
   name: java-1.8.0-openjdk
   state: present
