- name: install apache
  hosts: all
  become: yes
  tasks:
    - name: run apt-get update
      apt:
       update_cache: yes
    - name: install apache2
      apt:
        name: apache2
        state: present
    - name: start service
      systemd:
        name: apache2
        state: restarted
